### ISSUE TITLE
Have a selector for atributes.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#330] opened 2021-10-18 13:19 UTC
Currently you can use selectors for most things except abilities. If you could modify them it would allow making effects such as yellow, slow, suspicious, thin skinned, elderly, as well as several edges.

**Comment by SalieriC** [comment] 2021-10-19 16:18
Isn't this a duplicate of #327 ?

**Comment by javierriveracastro** [comment] 2021-10-19 16:19
Uppppssss... my fault, I have asked grendel to open this one.

**Comment by grendel111111** [comment] 2021-10-19 23:56
#327 is referring to a creature having a special ability like leap. This is the abilities like strength and vigor.

**Comment by SalieriC** [comment] 2021-10-20 10:51
> #327 is referring to a creature having a special ability like leap. This is the abilities like strength and vigor.

Then we should really agree on the correct terms here to avoid further confusion:

- Traits are Attributes and Skills.
- Attributes are the defining traits of a character (Agility, Smarts, Spirit, Strength and Vigor). All **Attributes** are Traits but not all Traits are Attributes.
- (Special) Abilities on the other hand are things rather unique to a character or creature. They can come in the form of a weapon, armour or something that fits no other category. Abilities are thus a unique term that should not be used in any other context but when referring to Special Abilities when talking about Savage Worlds as it would only cause confusion.

**Comment by grendel111111** [comment] 2021-10-20 13:16
Sorry, yes I got confused by terminology. I should have said Attributes.

**Comment by javierriveracastro** [comment] 2021-11-29 15:26
@bloy patch has addressed this.

**Closed as completed by javierriveracastro** 2021-11-29 15:26 UTC
