### ISSUE TITLE
Joker bonuses not being applied in combat.

### ISSUE THREAD

**Issue by sroakjp** [javierriveracastro/betteroll-swade#432] opened 2022-04-19 04:07 UTC
In my game last night we had several rounds where players drew the Joker. In all cases we did not see the bonus to trait rolls or to damage being applied in the results.

**Comment by javierriveracastro** [comment] 2022-04-19 14:35
Can you elaborate more, I have been testing it and Joker seems to work right.

If you can replicate it, please tell me the exact steps to do it. It could be related to some difference in how you open the sheet or some other small issue that becomes significant.

**Comment by sroakjp** [comment] 2022-04-19 15:28
I don't know how much to elaborate. The automatic initiative in SWADE dealt the player a Joker, which awarded all the players a bennie. He then made an attack roll using the better rolls 2 for SWADE card. When expanding the results the bonus for the Joker was not present. When he rolled damage the bonus from the Joker was not present.

**Comment by javierriveracastro** [comment] 2022-04-19 15:35
A step for step procedure (click by click), a video will be better. Also, is everything updated?

You can also make a test combat in your server and see if it works, maybe there is something there. There is more than a simple failure is going on here, but I have no idea of what. Note that this has been reported before, so something is going on, but I have no idea of what.

**Comment by SalieriC** [comment] 2022-04-19 15:39
I've seen this before as well, for a long time. But whenever I want to investigate it further, it suddenly seems to work. I have yet to find a fool-proof way of replicating it. :-S

**Comment by sroakjp** [comment] 2022-04-20 00:24
I did a couple of test combats and noticed two situations, one where the joker works, and one where it doesn't.
When I target another token with the selected token (the one with the Joker) and I click on an equipped weapon in that token's inventory, and then roll, everything works fine. Joker bonuses apply normally.
If I select a skill instead (say notice) no joker bonus. Even if I select fighting, no bonus.

So it appears to work when using a weapon or power in an attack. But not on regular trait rolls. 
Per the rules, the joker adds +2 to all trait and damage rolls. Not just attacks. So it should work when using any skill or attribute on the token's sheet, not just from weapons or powers.

**Comment by grendel111111** [comment] 2022-04-20 04:50
sroakjp:
Just adding to this: 
Are you using Token action HUD? I found that when I roll a skill from the Token HUD that isn't an attack it does not take the joker into account. When I roll the same Trait from the character sheet then it does use the joker bonus. If you are using token HUD try it from the sheet directly and see if it makes a difference. If it does then it is likely to be the way token action HUD is sending the request to BR2.

**Comment by SalieriC** [comment] 2022-04-20 06:38
I cannot reproduce any of that. I just tested it both on a player and on a gm account. Works all fine.

What did not apply the Joker however was when I opened the sheet of a (linked) PC from the sidebar, rather than from doublke clicking the token @javierriveracastro. In which case, the bonus from the Joker was never applied.

**Comment by javierriveracastro** [comment] 2022-04-20 06:46
@sroakjp Sorry but i can't reproduce it, I have already tested skill and attribute rolling. How do you open the sheet?. I already asked it before because it is a more likely cause. 

I have to test it more but SalieriC can be on it. It makes some sense that if the card is missing token info there could be problems relating it to the combat tracker.

**Comment by sroakjp** [comment] 2022-04-20 11:57
Token Action HUD appears to be the culprit. When I try it by double clicking the token and launching the skill or whatever directly from the sheet it works fine. If I launch weapon attack or power from the HUD it works fine. But for skills or attributes launched from the HUD no Joker.

So I think it is an issue for those guys. If you agree we can close this one and I'll open an issue with the Token Action HUD guys.

**Comment by javierriveracastro** [comment] 2022-04-20 11:59
No, even with no Token HUD, joker is not always applied, so I'd like to keep this issue open.

But feel free to open another one in token HUD.

**Comment by TheBiggerBadderBear** [comment] 2022-04-20 12:13
We had the same problem last night with Joker modifiers not always appearing. We're not using Token HUD. 

Confirmed that if you open the Actor Sheet from the sidebar/actors menu and roll, no Joker bonuses are applied. However if you open the Actor Sheet from the on scene Token, Joker bonuses are applied. This is with Actor Data linked. 

As most of my players leave their character sheets open in a separate window, this led to most of the joker bonuses not being applied throughout the session. I'll just remind them to close it and reopen from the Token itself in the meantime!

**Comment by javierriveracastro** [comment] 2022-04-20 14:44
Ok, the part about rolling from the sidebar should be solved.

Maybe, just maybe it will also solve the Token HUD and some other possible cases.

**Closed as completed by javierriveracastro** 2022-04-20 14:44 UTC
Labels: bug, question
