### ISSUE TITLE
Automated Animations don't work with Better Roll 2

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#278] opened 2021-07-27 18:21 UTC
Hi.

I asked the Automated Animations dev to make it work wit br2, but there is some kind of problem.

Is it possible to give him some help to make Automated Animations work with better roll 2?

Thank you

**Comment by SalieriC** [comment] 2021-07-29 13:38
Last info I had was that AA only supports BR2. XD
In any case, what exactly is the problem? Surely the author made some statement on what the problem is?

**Comment by brunocalado** [comment] 2021-07-29 13:57
System Roll
https://user-images.githubusercontent.com/4999783/127503888-b09bb43a-7adc-406b-b922-41360eff66b9.mp4

BR2 Roll
https://user-images.githubusercontent.com/4999783/127504013-e9b15033-f91b-4124-94c0-d1ef8b8f8b65.mp4

Using **javierrivera**:
```
{"id":"AUTOANIM","name":"Automated Animations","button_name":"AA","runSkillMacro":"PlayAA","selector_type":"item_type","selector_value":"weapon","defaultChecked":"on"}
```

Macro
```js
AutoAnimations.playAnimation(token, game.user.targets, item)
```


https://user-images.githubusercontent.com/4999783/127504904-7cd2cabd-9463-4780-a9c6-b8ceb7a948a4.mp4

**Comment by javierriveracastro** [comment] 2021-07-29 14:06
After looking at the source, that PlayAnimation use the "generic (dnd)" animation handler. There is a specific one for SWADE, but I can't see a way to access it from a macro.

Nor can I see nothing that I could do to make it work with BR. AFAIK we are at the mercy of the module author.

I'm going to close this bug, as a feel it really should be in Automated Animations issue tracker. If there is something concrete that I can do, please open another issue (or reopen this). If you want my input with the author (either in his bug tracker, discord, etc...) ping me in discord.

**Closed as completed by javierriveracastro** 2021-07-29 14:06 UTC
