### ISSUE TITLE
Ammo management issue

### ISSUE THREAD

**Issue by Alis-72** [javierriveracastro/betteroll-swade#379] opened 2022-01-02 21:49 UTC
When trying to reload therough BR2 card error "Uncaught Error: TypeError: actor.updateOwnedItem is not a function" pops and no ammo is added.
Tested with SWADE premium weapons and self-made ones

Foundry v9 b238
Better Rolls 2 v2.57

**Comment by SalieriC** [comment] 2022-01-02 23:58
Duplicate of #376 **and** #378 closing it for it is solved in Git.

**Closed as completed by SalieriC** 2022-01-02 23:58 UTC
Labels: duplicate
