### ISSUE TITLE
Sort don't sort well 

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#618] opened 2023-08-23 20:52 UTC
The IDs sort feature is not working well. It's working in reverse.

![image](https://github.com/javierriveracastro/betteroll-swade/assets/4999783/01850eb5-828e-4875-b972-62e4b7dbf92e)

```
  {
    id: "CH01PP",
    name: "+1 PP",
    button_name: "+1",
    "shotsUsed": "+1",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points"
  },
  {
    id: "CH02PP",
    name: "+2 PP",
    button_name: "+2",
    "shotsUsed": "+2",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points"
  },
  {
    id: "CH03PP",
    name: "+3 PP",
    button_name: "+3",
    "shotsUsed": "+3",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points"
  },
  {
    id: "CH04PP",
    name: "+4 PP",
    button_name: "+4",
    "shotsUsed": "+4",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points"
  },
  {
    id: "CH05PP",
    name: "+5 PP",
    button_name: "+5",
    "shotsUsed": "+5",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points"
  },
  {
    id: "CH06PP",
    name: "+6 PP",
    button_name: "+6",
    "shotsUsed": "+6",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points"
  },
  {
    id: "CH07PP",
    name: "+7 PP",
    button_name: "+7",
    "shotsUsed": "+7",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points"
  },
  {
    id: "CH08PP",
    name: "+8 PP",
    button_name: "+8",
    "shotsUsed": "+8",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points"
  },
  {
    id: "CH09PP",
    name: "+9 PP",
    button_name: "+9",
    "shotsUsed": "+9",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points"
  },
```

**Comment by javierriveracastro** [comment] 2023-08-25 14:41
I can't reproduce this... how are you adding the actions?

BTW, I'd add that power point actions to the module if you don't mind....

**Comment by javierriveracastro** [comment] 2023-08-25 15:24
Now that I'm writing the next version changelog I see that I have already fixed this before. No surprise it is working for me and not for you. Closing it, feel free to open it again if it doesn't work in 3.42

**Closed as completed by javierriveracastro** 2023-08-25 15:24 UTC

**Comment by brunocalado** [comment] 2023-08-25 17:11
It's working well on 342 
thank you
