### ISSUE TITLE
Reload throwing TypeError: actor.updateOwnedItem is not a function

### ISSUE THREAD

**Issue by zombiebrak** [javierriveracastro/betteroll-swade#378] opened 2022-01-02 21:43 UTC
![Screenshot 2022-01-02 164324](https://user-images.githubusercontent.com/16766409/147890235-68277b8f-3a99-48c3-9754-bb08afe8801c.png)

**Comment by SalieriC** [comment] 2022-01-02 23:57
Duplicate of #376, closing it for it is solved in Git.

**Closed as completed by SalieriC** 2022-01-02 23:57 UTC
Labels: duplicate
