### ISSUE TITLE
Power Point management broken with SWADE version 2.1.0 and above.

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#538] opened 2022-11-20 16:57 UTC
Version 2.1.0 of SWADE introduced a breaking change regarding power points which means that the power point management of BRSW is now non-functional. It doesn't find the power point pool of the power and is thus unable to change it.
Here are the changes detailed: https://gitlab.com/peginc/swade/-/blob/develop/CHANGELOG.md#changed-2

**Comment by javierriveracastro** [comment] 2022-11-21 07:57
This should already be addressed (not released yet). Have you reproduced the problem with git version?

**Comment by javierriveracastro** [comment] 2022-11-21 15:04
Seems to be working for me, so I will close this. Feel free to reopen if you find it is not really solved.

**Closed as completed by javierriveracastro** 2022-11-21 15:04 UTC
Labels: bug

**Comment by SalieriC** [comment] 2022-11-21 16:29
Yeah no, didn't test the git version. Sorry about that.
