### ISSUE TITLE
Change Unshake & Unstun Cards to the system feature `game.swade.effectCallbacks.set("shaken", somefunction)`

### ISSUE THREAD

**Issue by SalieriC** [javierriveracastro/betteroll-swade#478] opened 2022-09-05 07:33 UTC
It seems the setting which should suppress the BR2 status removal card on combat round start is non-functional. I have not properly tested this yet so it needs confirmation. Might be just me.
In any case, if the card *is* shown, it should suppress the default unshake function provided by SWADE v.1.2.x.

**Comment by javierriveracastro** [comment] 2022-09-19 13:40
It works for me, but you need to reload after changing the setting. I should probably make it do it automatically.

What it does to me is disabling the system dialog even when no card is shown, and that doesn't make sense, specially now that it requires SWIM and SWIM does have a setting for it.

**Comment by javierriveracastro** [comment] 2022-09-19 13:44
No, it works the problem is that the status duration persists. I mean if I added shaken when br2 (and a combat) is active it will still use system behavior. I'll close this as i can't reproduce it. Please check again and re-open it if it still happens to you.

**Comment by SalieriC** [comment] 2022-09-19 14:00
*SUCC
If you can't reproduce I'll rephrase it. As of SWADE v.2, the BR2 function to unshake should (optionally) use `game.swade.effectCallbacks.set("shaken", somefunction)` instead of disabling the chat card and does it's own thing. This way it will use a core feature, making the code slimmer instead of reinventing the wheel. Making this optional will also allow users to use core or other modules functions.

**Comment by javierriveracastro** [comment] 2022-09-19 14:48
Ahhh... Swade v2, not 1.2 ;P.

Ok, but we need v10 compatibility for that. It is also not a bug.

**Comment by SalieriC** [comment] 2022-09-19 14:50
Eh, sorry, meant to say 1.2.
Original was a bug but apparently just on my end or maybe I missed the reload. `game.swade.effectCallbacks.set("shaken", somefunction)` is available in 1.2 as well though.

**Comment by javierriveracastro** [comment] 2022-09-19 14:51
Then for sure it will be better to use it.

**Comment by javierriveracastro** [comment] 2022-10-20 15:22
Done.

**Closed as completed by javierriveracastro** 2022-10-20 15:22 UTC
Labels: enhancement
