### ISSUE TITLE
Repeated Automated Animations effects when ammo mangement is enabled

### ISSUE THREAD

**Issue by hakeem4321** [javierriveracastro/betteroll-swade#673] opened 2024-01-22 19:01 UTC
When using automated ammo management alongside Automated Animations, the effects play twice.

How to reproduce:
1- Automatic Ammo Management must be enabled from the system configuration
2- Ammo subtraction is enabled (it doesn't matter if it's automatically toggled or manual)
enable Subtract Ammo won't trigger the issue, it seems related how the Better Rolls cards work, because it works fine when using the system's default rolling method, this also doesn't happen to automatic power point management

**Comment by javierriveracastro** [comment] 2024-01-23 07:38
Isn't any configuration needed on AA to reproduce this?

Given that it works using name, Does it happen with some particular item or kind of items?

**Comment by hakeem4321** [comment] 2024-01-24 16:46
> Isn't any configuration needed on AA to reproduce this?
>
yes, you first need to set up the effect using AA, it seems to trigger as long as the effect is played on the attack roll (doesn't trigger when using templates effects for example)

i have tried a few other things:
- it works on every reload procedure except for None, which is the only where the system doesn't reduce shots automatically
- weapons that have 0 maximum shots don't trigger the issue (this again seems related to the reloading functionality, as having current shots while the maximum is 0 plays the effect normally as the shots aren't reduced)

> Given that it works using name, Does it happen with some particular item or kind of items?
>
only with weapons with shots/ammo so far, i was unable to replicate it on active effects and powers, they work normally

**Comment by javierriveracastro** [comment] 2024-01-25 07:44
Thanks I will try to reproduce it. It's likely that I have to get back to you as I have never used AA.

**Comment by javierriveracastro** [comment] 2024-01-31 15:08
Sorry, but I'm totally unable to reproduce it.

**Comment by hakeem4321** [comment] 2024-02-01 20:17
https://youtu.be/c74FjwrAA6A
here's a video a recorded, i thought the issue might be related to the browser (i was using firefox) but it wasn't, it also tried it on both a local foundry hosting and on Forge, same issue

**Comment by javierriveracastro** [comment] 2024-02-02 08:24
Ahhhh... now I see it. It's quite subtle.

**Comment by javierriveracastro** [comment] 2024-02-02 14:31
Nope, I have even delete shooting to use "uniskilled attempt".

[Screencast_20240202_152907.webm](https://github.com/javierriveracastro/betteroll-swade/assets/8113700/e98980e1-35c9-438f-b343-7fe64ef90b1f)

Something else must be going on.

**Comment by hakeem4321** [comment] 2024-02-02 14:33
did you add ammo and check the reload method? because the warning appeared in the video

**Comment by javierriveracastro** [comment] 2024-02-02 14:37
Yes, I have just tested it so many times that I have run out of ammo:

![imaxe](https://github.com/javierriveracastro/betteroll-swade/assets/8113700/0afaccd4-f467-4f35-906a-f02a9df4a3f4)

**Comment by javierriveracastro** [comment] 2024-02-02 14:39
I have also removed ammunition. damage and range...

**Comment by javierriveracastro** [comment] 2024-02-02 14:46
Can you record a video like this?

[Screencast_20240202_154455.webm](https://github.com/javierriveracastro/betteroll-swade/assets/8113700/e2babde5-1fa5-49ac-822d-925fa19078a8)

The important bits is having debugging in AA enabled and the console open.

**Comment by hakeem4321** [comment] 2024-02-02 14:54
https://youtu.be/NJXqTNFE3fQ i apologize the video isn't uploaded on here, github doesn't support mkv files

**Comment by hakeem4321** [comment] 2024-02-02 14:56
also real quick, i tried it with one of my players and when he shoots the effects play rapidly but when i shoot they have a larger gap, we're both using the same character against the same target

**Comment by javierriveracastro** [comment] 2024-02-02 15:04
It only shows one `DEBUG | Automated Animations | range Animation Start" 
Object { primary: {…}, secondary: false, sourceFX: false, targetFX: false, macro: false }
[constants.js:3:16](http://localhost:30000/modules/autoanimations/src/constants/constants.js)`to me.

I'm sorry but I have absolutely no idea of what is going on here...

It must be some kind of race condition. Let me try to check how AA decides to play an animation.

**Comment by hakeem4321** [comment] 2024-02-02 15:16
and just to be sure, did you set the animations to play on trait or damage rolls?

**Comment by javierriveracastro** [comment] 2024-02-02 15:25
Got it.

AA is hooking both to `"BRSW-RollItem"`and to `"swadeConsumeItem"`. This is why it shown the animation twice.

Now in my test world, "swadeConsumeItem" is throwing an error and preventing the second animation to be shown. In yours it likely isn't doing that.

**Comment by javierriveracastro** [comment] 2024-02-02 15:41
> and just to be sure, did you set the animations to play on trait or damage rolls?

That shouldn't matter. It is only checked in the swade_action Hook.

**Comment by javierriveracastro** [comment] 2024-03-05 14:38
I don't think that this could be addressed on BR2, so I'm closing it. Please, feel free to reopen it if you don't agree.

**Closed as completed by javierriveracastro** 2024-03-05 14:38 UTC
