### ISSUE TITLE
Add card to Skills!

### ISSUE THREAD

**Issue by brunocalado** [javierriveracastro/betteroll-swade#268] opened 2021-07-21 17:13 UTC
Hi!

Can you make buttons for edges/hindrances show up in the skills card?

This could be useful for:
![image](https://user-images.githubusercontent.com/4999783/126530849-2b90529a-5ed0-47be-96c0-d1e22400f6d6.png)

![Uploading image.png…]()

etc

**Comment by javierriveracastro** [comment] 2021-07-21 17:18
Sorry, another closed issue today. This is (unless I'm mistaken) a duplicate off #227

**Closed as completed by javierriveracastro** 2021-07-21 17:18 UTC

**Comment by brunocalado** [comment] 2021-07-21 17:33
I tried to match with #227, but I think It's a different issue. But, my english is not the best...

This is not for combat. It's for skills like Persuasion, Intimidation, Survival etc. They could have a button to add bonus too.
![image](https://user-images.githubusercontent.com/4999783/126533535-6704524d-548f-4e1f-bf5c-f88c6f32b448.png)

**Comment by javierriveracastro** [comment] 2021-07-21 18:40
Ejem... you english is clearly better than mine. I mean #221
