### ISSUE TITLE
Enabling BR2 is removing the Sidebar Tabs minimise icon

### ISSUE THREAD

**Issue by steveculshaw** [javierriveracastro/betteroll-swade#636] opened 2023-09-19 13:55 UTC
Enabling BR2 is removing the Sidebar Tabs minimise icon

With BR2 (and SUCC) modules disabled, I have the usual Sidebar with the minimise arrow icon ...
![FVTT-sidebar-minimise](https://github.com/javierriveracastro/betteroll-swade/assets/64320/483cb729-dbc4-471b-af21-4dde3339fd94)

But when I enable BR2 (& SUCC), the minimise arrow disappears ...
![FVTT-sidebar-minimise-missing-with-BR2-activated](https://github.com/javierriveracastro/betteroll-swade/assets/64320/319b3ab2-8d6f-4a98-a129-2fb0f23313f5)

This is on ...
FVTT v11.308
BR2 v3.50

**Comment by javierriveracastro** [comment] 2023-09-19 14:44
DUplicate of #635 635

**Closed as completed by javierriveracastro** 2023-09-19 14:44 UTC

**Comment by steveculshaw** [comment] 2023-09-19 15:16
@javierriveracastro  Sorry, missed the other issue  :-(
